site_name: Solar SIEM Knowledge Base
site_description: База знаний Solar SIEM
site_url: https://kb.heftech.ru/
repo_url: https://github.com/solar-siem/knowledge-base
repo_name: solar-siem/knowledge-base

copyright: >
  <a href="https://heftech.ru" target="_blank" rel="noopener">© 2026 ООО «Гефест Технолоджиз»</a>

extra:
  generator: false

theme:
  name: material
  language: ru
  logo: assets/logo.svg
  favicon: assets/logo.svg
  font:
    text: Inter
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Светлая тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Тёмная тема
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - toc.follow
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

extra_css:
  - assets/stylesheets/light-theme.css
  - assets/stylesheets/dark-theme.css

plugins:
  - search:
      lang: ru

nav:
  - Главная: index.md
  - Установка:
      - Обзор: installation/overview.md
      - "Выпуск SSL-сертификата с помощью AD CS": installation/ssl_cert_creation.md
  - Сбор событий:
      - Обзор: data-collection/overview.md
  - Детектирование:
      - Обзор: detection/overview.md
  - Реагирование:
      - Обзор: response/overview.md
      - "Запуск hydra (Linux)": response/hydra-linux.md
      - "Очистка журнала событий (Windows)": response/log-clearing.md
  - Решение проблем:
      - Обзор: troubleshooting/overview.md
      - "Cбор диагностического архива": troubleshooting/log-collection.md
      - "Диагностика и управление кластером Kubernetes через k9s": troubleshooting/k9s.md


